repos:
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    args: [--rcfile=./.pylintrc]
    types: [python]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--settings-file=./pyproject.toml/]
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    args: [--config=./pyproject.toml]